<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="testcases.OpenAccount"
           tests="6"
           failures="6"
           errors="0"
           skipped="0"
           time="50.149">
  <properties />
      <testcase name="OpenAccount" time="5.606">
            <failure type="java.lang.IndexOutOfBoundsException"
                  message="Index 4 out of bounds for length 4"
              >
<![CDATA[java.lang.IndexOutOfBoundsException: Index 4 out of bounds for length 4
  java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
  java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
  java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
  java.base/java.util.Objects.checkIndex(Objects.java:373)
  java.base/java.util.ArrayList.get(ArrayList.java:426)
  testcases.OpenAccount.OpenAccount(OpenAccount.java:45)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.base/java.lang.reflect.Method.invoke(Method.java:564)
  org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
  org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
  org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
  org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
  org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
  org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
  org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
  java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
  org.testng.TestRunner.privateRun(TestRunner.java:806)
  org.testng.TestRunner.run(TestRunner.java:601)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
  org.testng.SuiteRunner.run(SuiteRunner.java:330)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
  org.testng.TestNG.runSuites(TestNG.java:1099)
  org.testng.TestNG.run(TestNG.java:1067)
  com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
  com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
]]>
      </failure>

          </testcase>
      <testcase name="OpenAccount" time="17.250">
            <failure type="java.lang.IndexOutOfBoundsException"
                  message="Index 4 out of bounds for length 4"
              >
<![CDATA[java.lang.IndexOutOfBoundsException: Index 4 out of bounds for length 4
  java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
  java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
  java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
  java.base/java.util.Objects.checkIndex(Objects.java:373)
  java.base/java.util.ArrayList.get(ArrayList.java:426)
  testcases.OpenAccount.OpenAccount(OpenAccount.java:45)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.base/java.lang.reflect.Method.invoke(Method.java:564)
  org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
  org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
  org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
  org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
  org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
  org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
  org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
  java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
  org.testng.TestRunner.privateRun(TestRunner.java:806)
  org.testng.TestRunner.run(TestRunner.java:601)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
  org.testng.SuiteRunner.run(SuiteRunner.java:330)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
  org.testng.TestNG.runSuites(TestNG.java:1099)
  org.testng.TestNG.run(TestNG.java:1067)
  com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
  com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
]]>
      </failure>

          </testcase>
      <testcase name="OpenAccount" time="11.335">
            <failure type="java.lang.IndexOutOfBoundsException"
                  message="Index 4 out of bounds for length 4"
              >
<![CDATA[java.lang.IndexOutOfBoundsException: Index 4 out of bounds for length 4
  java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
  java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
  java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
  java.base/java.util.Objects.checkIndex(Objects.java:373)
  java.base/java.util.ArrayList.get(ArrayList.java:426)
  testcases.OpenAccount.OpenAccount(OpenAccount.java:45)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.base/java.lang.reflect.Method.invoke(Method.java:564)
  org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
  org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
  org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
  org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
  org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
  org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
  org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
  java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
  org.testng.TestRunner.privateRun(TestRunner.java:806)
  org.testng.TestRunner.run(TestRunner.java:601)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
  org.testng.SuiteRunner.run(SuiteRunner.java:330)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
  org.testng.TestNG.runSuites(TestNG.java:1099)
  org.testng.TestNG.run(TestNG.java:1067)
  com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
  com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
]]>
      </failure>

          </testcase>
      <testcase name="OpenAccount" time="5.878">
            <failure type="java.lang.IndexOutOfBoundsException"
                  message="Index 4 out of bounds for length 4"
              >
<![CDATA[java.lang.IndexOutOfBoundsException: Index 4 out of bounds for length 4
  java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
  java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
  java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
  java.base/java.util.Objects.checkIndex(Objects.java:373)
  java.base/java.util.ArrayList.get(ArrayList.java:426)
  testcases.OpenAccount.OpenAccount(OpenAccount.java:45)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.base/java.lang.reflect.Method.invoke(Method.java:564)
  org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
  org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
  org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
  org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
  org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
  org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
  org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
  java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
  org.testng.TestRunner.privateRun(TestRunner.java:806)
  org.testng.TestRunner.run(TestRunner.java:601)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
  org.testng.SuiteRunner.run(SuiteRunner.java:330)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
  org.testng.TestNG.runSuites(TestNG.java:1099)
  org.testng.TestNG.run(TestNG.java:1067)
  com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
  com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
]]>
      </failure>

          </testcase>
      <testcase name="OpenAccount" time="6.314">
            <failure type="java.lang.IndexOutOfBoundsException"
                  message="Index 4 out of bounds for length 4"
              >
<![CDATA[java.lang.IndexOutOfBoundsException: Index 4 out of bounds for length 4
  java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
  java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
  java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
  java.base/java.util.Objects.checkIndex(Objects.java:373)
  java.base/java.util.ArrayList.get(ArrayList.java:426)
  testcases.OpenAccount.OpenAccount(OpenAccount.java:45)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.base/java.lang.reflect.Method.invoke(Method.java:564)
  org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
  org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
  org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
  org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
  org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
  org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
  org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
  java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
  org.testng.TestRunner.privateRun(TestRunner.java:806)
  org.testng.TestRunner.run(TestRunner.java:601)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
  org.testng.SuiteRunner.run(SuiteRunner.java:330)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
  org.testng.TestNG.runSuites(TestNG.java:1099)
  org.testng.TestNG.run(TestNG.java:1067)
  com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
  com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
]]>
      </failure>

          </testcase>
      <testcase name="OpenAccount" time="3.766">
            <failure type="java.lang.IndexOutOfBoundsException"
                  message="Index 4 out of bounds for length 4"
              >
<![CDATA[java.lang.IndexOutOfBoundsException: Index 4 out of bounds for length 4
  java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
  java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
  java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
  java.base/java.util.Objects.checkIndex(Objects.java:373)
  java.base/java.util.ArrayList.get(ArrayList.java:426)
  testcases.OpenAccount.OpenAccount(OpenAccount.java:45)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.base/java.lang.reflect.Method.invoke(Method.java:564)
  org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
  org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
  org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
  org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
  org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
  org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
  org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
  java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
  org.testng.TestRunner.privateRun(TestRunner.java:806)
  org.testng.TestRunner.run(TestRunner.java:601)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
  org.testng.SuiteRunner.run(SuiteRunner.java:330)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
  org.testng.TestNG.runSuites(TestNG.java:1099)
  org.testng.TestNG.run(TestNG.java:1067)
  com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
  com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
]]>
      </failure>

          </testcase>
  

  

  

</testsuite>
